favoritePlaces = ['alethkar' , 'shinovar' , 'iriali' , 'thaylenah' , 'jah keved' , 'azir']
print(favoritePlaces)
print("List in sorted order: ")
print(sorted(favoritePlaces))
print("List in actual order: ")
print(favoritePlaces)
print("List in sorted reverse order: ")
varSorted  = sorted(favoritePlaces)
varSorted.reverse()
print(varSorted)
print("List in its original order: ")
print(favoritePlaces)
favoritePlaces.reverse()
print("List is change in reverse order: ")
print(favoritePlaces)
favoritePlaces.reverse()
print("List is change in reverse order again: ")
print(favoritePlaces)
favoritePlaces.sort()
print("List finally in sorted order: " )
print(favoritePlaces)
print("List finally in sorted reverse order: " )
favoritePlaces.sort(reverse = True)
print(favoritePlaces)
